spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverclassname: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/star
        username: root
        password: root
        initialSize: 2
        minIdle: 2
        maxActive: 10
        
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.gui.star.dal.model  # 注意：对应实体类的路径
  
mybatis-plus: 
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.gui.star.dal.model
  configuration:
    map-underscore-to-camel-case: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl